apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "awstestapplication-101"
  description: "awstestapplication"

  links:
    - url: https://github.com/RohanAwasthi/my-python-application-101
      title: "awstestapplication-101"
      icon: code

  labels:
    system: web-apps
    trackid: "awstestapplication101"
    environmentname: my-python-env-101

  tags:
    - my-python-application-101
    - aws
    - "applicationtype-webapplication"

  annotations:
    # add elastic beanstalk annotation
    jenkins.io/github-folder: 'custom-actions/tf-awstestapplication-101'
    github.com/project-slug: RohanAwasthi/my-python-application-101
    backstage.io/techdocs-ref: dir:.

spec:
  type: service
  lifecycle: experimental
  system: elasticbeanstalk
  owner: "neelesh.shekhar"
